FROM node:20-alpine

WORKDIR /app/frontend

COPY ./frontend/package.json ./frontend/package-lock.json* ./

RUN npm install

COPY ./frontend .

EXPOSE 3000 3001

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
